export const auditoriums = [
  {
    id: 1,
    name: "Grand Hall",
    location: "Main Campus, Building A",
    capacity: 500,
    hasProjector: true,
    hasSoundSystem: true,
    hasAirConditioning: true,
    hasStageLighting: true,
    hasWifi: true,
    hasWheelchairAccess: true,
    hasGreenRoom: true,
    hasParking: true,
    hasPodium: true,
    hasVideoRecording: false,
    active: true,
  },
  {
    id: 2,
    name: "North Conference Room",
    location: "Innovation Center",
    capacity: 150,
    hasProjector: true,
    hasSoundSystem: true,
    hasAirConditioning: true,
    hasStageLighting: false,
    hasWifi: true,
    hasWheelchairAccess: true,
    hasGreenRoom: false,
    hasParking: true,
    hasPodium: true,
    hasVideoRecording: true,
    active: true,
  },
  {
    id: 3,
    name: "Westwood Theater",
    location: "Arts & Culture Block",
    capacity: 300,
    hasProjector: true,
    hasSoundSystem: true,
    hasAirConditioning: true,
    hasStageLighting: true,
    hasWifi: false,
    hasWheelchairAccess: false,
    hasGreenRoom: true,
    hasParking: false,
    hasPodium: true,
    hasVideoRecording: true,
    active: true,
  },
  {
    id: 4,
    name: "Small Seminar Hall",
    location: "Library Building, Floor 3",
    capacity: 50,
    hasProjector: true,
    hasSoundSystem: false,
    hasAirConditioning: true,
    hasStageLighting: false,
    hasWifi: true,
    hasWheelchairAccess: true,
    hasGreenRoom: false,
    hasParking: true,
    hasPodium: false,
    hasVideoRecording: false,
    active: true,
  }
];